name: Auto-merge on "merge" comment

on:
  issue_comment:
    types: [created]

jobs:
  auto-merge:
    # Run only when the comment is on a pull request and the body is exactly "merge"
    if: >
      github.event.issue.pull_request &&
      github.event.comment.body == 'merge'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Merge the pull request
        uses: peter-evans/merge-pull-request@v3
        with:
          pull-request: ${{ github.event.issue.number }}
          method: squash
